[project]
name = "bert-finetune"
version = "1.0.0"
description = "Full fine tuning BERT"
license = "Apache-2.0"
dependencies = [
    "datasets>=4.5.0",
    "evaluate>=0.4.6",
    "numpy>=2.4.2",
    "scikit-learn>=1.8.0",
    "torch>=2.10.0",
    "transformers[torch]>=5.2.0",
]
